- modules/log.js
- modules/log/checkPanoptoContainer.js
- package-lock.json
- package.json
- Added panopto check for code cleaner
> Added a panopto iframe check to code cleaner

- modules/log.js
- modules/log/checkHeadings.js
- modules/log/checkTitleAndH1.js
- package-lock.json
- package.json
- Added headings check to log.js
- Added code for checking headings within content bodies
> Added headings check for content bodies

- modules/log/checkHeader.js
- package-lock.json
- package.json
- Added a function to check for "syllabus" in the file path and skip additional checks if "syllabus" exists
- Bumped version number
> Skip header check if file path contains syllabus

- modules/clean.js
- modules/clean/cleanElementAttributes.js
- modules/clean/cleanTableAttributes.js
- modules/clean/cleanTextElements.js
- modules/clean/removeRolePresentation.js
- modules/clean/removeTargetAttributes.js
- package.json
- Create a "clean" directory to add all clean modules
- Created a separate module for each clean function
- Consolidated all clean functions into clean.js
> Added separate modules for each clean function

- config.js
- Added config file in the root of the app
- Kept it empty except for export statement
> Added config file

- gulpfile.js
- modules/imageCheck.js
- package-lock.json
- package.json
- Added new file for checking image file sizes
- Edited main gulpfile.js file
> Added check for image files

- modules/log.js
- modules/log/checkJquery.js
- package-lock.json
- package.json
- Created new function to check for jquery script and log if exists
- Added new jquery check to `log.js`
> Created function to log if jquery script exists

- modules/clean.js
- modules/clean/matchTitleToH1.js
- package-lock.json
- package.json
- Create js module with function to match title tag to h1
- Add function to clean.js
> Add function to match title tag to h1

- modules/log.js
- modules/log/checkJsScripts.js
- package-lock.json
- package.json
- Added a check to see if any script tags exist outside the head
- Added function into log.js
> Added a check for any script tags outside head section

- modules/clean.js
- modules/clean/cleanImageAttributes.js
- package-lock.json
- package.json
- Create js module with function to remove attrs, add alt attr if it doesn't exist, and replace `<p>` with `<div>` if `<p>` is the parent of `<img>`
- Add function to clean.js
> Add function to clean images

- config.js
- modules/log/checkTables.js
- package-lock.json
- package.json
- Edited checkTable file that logs table errors
- Added a check for vertical tables for classes and also for thead checks
> Added a check for vertical tables

- modules/log/checkContentBody.js
- package-lock.json
- package.json
- Created an array to check for invalid nested elements (whether classes, ids, or tags) within a content-body
- Added `.content-body` and `header` checks within array; more elements can be added later if needed
> Added array check for invalid nested elements within a content-body

- config.js
- modules/clean.js
- modules/clean/removeContentBodyInnerTags.js
- package-lock.json
- package.json
- Added configurable variable in config.js
- Added new file to parse through content bodies and remove specific tags
> Added a file to remove specific tags from content body

- package-lock.json
- package.json
- Updated jsdom and gulp-cli
- All other npm packages (other than gulp) were up to date
> Updated npm dependencies besides gulp

- modules/log.js
- modules/log/checkIframeOnlyPages.js
- package-lock.json
- package.json
- `checkIframeOnlyPages.js` checks to see if `<body>` only contains `<iframe>` elements
- If `true` only `checkIframeTitles.js` will run
- If `false` all other checks will run
> Add check for iframe only pages

- modules/log/checkContentWrapper.js
- package-lock.json
- package.json
- Update `checkContentWrapper.js` to include `#first-column`
> Add first column check to checkContentWrapper

- modules/log.js
- package-lock.json
- package.json
I removed the increment functionality in a previous PR. This is to add it back in so that files that have errors are numbered correctly.
> Add error count increment

- README.md
- modules/clean/cleanElementAttributes.js
- modules/clean/cleanImageAttributes.js
- modules/clean/cleanTableAttributes.js
- modules/clean/cleanTextElements.js
- modules/clean/matchTitleToH1.js
- modules/clean/removeContentBodyInnerTags.js
- modules/clean/removeJQueryScript.js
- modules/clean/removeRolePresentation.js
- modules/clean/removeTargetAttributes.js
- modules/hooks/domTransform.js
- package-lock.json
- package.json
- Added through2 - new npm package
- Removed gulp-dom - deprecated gulp package
- Moved all dependencies to dev dependencies
- Replaced instances of gulp dom with new helper function utilizing js dom and through2
> Replace gulp dom: 9613894638

- frontend/src/App.jsx
- frontend/src/components/Toast.jsx
- frontend/src/styles/styles.css
- package-lock.json
- package.json
- Added total errors in a visible spot for users to see throughout the editing process.
> Add file sidebar error numbers: 9999808668

- frontend/src/App.jsx
- frontend/src/components/LoadingBar.jsx
- frontend/src/styles/LoadingBar.css
- package-lock.json
- package.json
- Added loading bar for longer processes like scanning, cleaning, and saving.
> Add loading bars: 10065493310

- frontend/src/App.jsx
- frontend/src/components/FileErrorGroup.jsx
- modules/scanRunner.js
- server/index.js
- Added error reporting for image sizes being more than maximum
> Add image reporting: 10065509294
